src/Entity/Restaurante.php
<?php

namespace App\Entity;

use App\Repository\RestauranteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RestauranteRepository::class)]
class Restaurante
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $street_address = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 6)]
    private ?string $latitude = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 6)]
    private ?string $longitude = null;

    #[ORM\Column(length: 255)]
    private ?string $city_name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $popularity_rate = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2, nullable: true)]
    private ?string $satisfaction_rate = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2)]
    private ?string $last_avg_price = null;

    #[ORM\Column]
    private ?int $total_reviews = null;

    #[ORM\Column(length: 255)]
    private ?string $uidentifier = null;

    #[ORM\ManyToMany(targetEntity: Segmento::class, inversedBy: 'restaurantes')]
    private Collection $segmentos;

    public function __construct()
    {
        $this->segmentos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStreetAddress(): ?string
    {
        return $this->street_address;
    }

    public function setStreetAddress(?string $street_address): static
    {
        $this->street_address = $street_address;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getCityName(): ?string
    {
        return $this->city_name;
    }

    public function setCityName(string $city_name): static
    {
        $this->city_name = $city_name;

        return $this;
    }

    public function getPopularityRate(): ?string
    {
        return $this->popularity_rate;
    }

    public function setPopularityRate(string $popularity_rate): static
    {
        $this->popularity_rate = $popularity_rate;

        return $this;
    }

    public function getSatisfactionRate(): ?string
    {
        return $this->satisfaction_rate;
    }
    
    public function setSatisfactionRate(?string $satisfaction_rate): static
    {
        $this->satisfaction_rate = $satisfaction_rate;
    
        return $this;
    }

    public function getLastAvgPrice(): ?string
    {
        return $this->last_avg_price;
    }

    public function setLastAvgPrice(string $last_avg_price): static
    {
        $this->last_avg_price = $last_avg_price;

        return $this;
    }

    public function getTotalReviews(): ?int
    {
        return $this->total_reviews;
    }

    public function setTotalReviews(int $total_reviews): static
    {
        $this->total_reviews = $total_reviews;

        return $this;
    }

    public function getUidentifier(): ?string
    {
        return $this->uidentifier;
    }

    public function setUidentifier(string $uidentifier): static
    {
        $this->uidentifier = $uidentifier;

        return $this;
    }

    /**
     * @return Collection<int, Segmento>
     */
    public function getSegmentos(): Collection
    {
        return $this->segmentos;
    }

    public function addSegmento(Segmento $segmento): static
    {
        if (!$this->segmentos->contains($segmento)) {
            $this->segmentos->add($segmento);
        }

        return $this;
    }

    public function removeSegmento(Segmento $segmento): static
    {
        $this->segmentos->removeElement($segmento);

        return $this;
    }
}

src/Form/RestauranteType.php
<?php

namespace App\Form;

use App\Entity\Restaurante;
use App\Entity\Segmento;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestauranteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('street_address')
            ->add('latitude')
            ->add('longitude')
            ->add('city_name')
            ->add('popularity_rate')
            ->add('satisfaction_rate')
            ->add('last_avg_price')
            ->add('total_reviews')
            ->add('uidentifier')
            ->add('segmentos', EntityType::class, [
                'class' => Segmento::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurante::class,
        ]);
    }
}

src/Controller/RestauranteController.php
<?php

namespace App\Controller;

use App\Entity\Restaurante;
use App\Form\RestauranteType;
use App\Repository\RestauranteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/restaurante')]
class RestauranteController extends AbstractController
{
    #[Route('/', name: 'app_restaurante_index', methods: ['GET'])]
    public function index(RestauranteRepository $restauranteRepository): Response
    {
        return $this->render('restaurante/index.html.twig', [
            'restaurantes' => $restauranteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_restaurante_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $restaurante = new Restaurante();
        $form = $this->createForm(RestauranteType::class, $restaurante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($restaurante);
            $entityManager->flush();

            return $this->redirectToRoute('app_restaurante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('restaurante/new.html.twig', [
            'restaurante' => $restaurante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_restaurante_show', methods: ['GET'])]
    public function show(Restaurante $restaurante): Response
    {
        return $this->render('restaurante/show.html.twig', [
            'restaurante' => $restaurante,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_restaurante_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Restaurante $restaurante, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RestauranteType::class, $restaurante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_restaurante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('restaurante/edit.html.twig', [
            'restaurante' => $restaurante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_restaurante_delete', methods: ['POST'])]
    public function delete(Request $request, Restaurante $restaurante, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurante->getId(), $request->request->get('_token'))) {
            $entityManager->remove($restaurante);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_restaurante_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/restaurante/_delete_form.html.twig
<form method="post" action="{{ path('app_restaurante_delete', {'id': restaurante.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurante.id) }}">
    <button class="btn">Delete</button>
</form>

templates/restaurante/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/restaurante/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Restaurante{% endblock %}

{% block body %}
    <h1>Edit Restaurante</h1>

    {{ include('restaurante/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_restaurante_index') }}">back to list</a>

    {{ include('restaurante/_delete_form.html.twig') }}
{% endblock %}

templates/restaurante/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurante index{% endblock %}

{% block body %}
    <h1>Restaurante index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Street_address</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>City_name</th>
                <th>Popularity_rate</th>
                <th>Satisfaction_rate</th>
                <th>Last_avg_price</th>
                <th>Total_reviews</th>
                <th>Uidentifier</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for restaurante in restaurantes %}
            <tr>
                <td>{{ restaurante.id }}</td>
                <td>{{ restaurante.name }}</td>
                <td>{{ restaurante.streetAddress }}</td>
                <td>{{ restaurante.latitude }}</td>
                <td>{{ restaurante.longitude }}</td>
                <td>{{ restaurante.cityName }}</td>
                <td>{{ restaurante.popularityRate }}</td>
                <td>{{ restaurante.satisfactionRate }}</td>
                <td>{{ restaurante.lastAvgPrice }}</td>
                <td>{{ restaurante.totalReviews }}</td>
                <td>{{ restaurante.uidentifier }}</td>
                <td>
                    <a href="{{ path('app_restaurante_show', {'id': restaurante.id}) }}">show</a>
                    <a href="{{ path('app_restaurante_edit', {'id': restaurante.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_restaurante_new') }}">Create new</a>
{% endblock %}

templates/restaurante/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Restaurante{% endblock %}

{% block body %}
    <h1>Create new Restaurante</h1>

    {{ include('restaurante/_form.html.twig') }}

    <a href="{{ path('app_restaurante_index') }}">back to list</a>
{% endblock %}

templates/restaurante/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurante{% endblock %}

{% block body %}
    <h1>Restaurante</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ restaurante.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ restaurante.name }}</td>
            </tr>
            <tr>
                <th>Street_address</th>
                <td>{{ restaurante.streetAddress }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ restaurante.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ restaurante.longitude }}</td>
            </tr>
            <tr>
                <th>City_name</th>
                <td>{{ restaurante.cityName }}</td>
            </tr>
            <tr>
                <th>Popularity_rate</th>
                <td>{{ restaurante.popularityRate }}</td>
            </tr>
            <tr>
                <th>Satisfaction_rate</th>
                <td>{{ restaurante.satisfactionRate }}</td>
            </tr>
            <tr>
                <th>Last_avg_price</th>
                <td>{{ restaurante.lastAvgPrice }}</td>
            </tr>
            <tr>
                <th>Total_reviews</th>
                <td>{{ restaurante.totalReviews }}</td>
            </tr>
            <tr>
                <th>Uidentifier</th>
                <td>{{ restaurante.uidentifier }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_restaurante_index') }}">back to list</a>

    <a href="{{ path('app_restaurante_edit', {'id': restaurante.id}) }}">edit</a>

    {{ include('restaurante/_delete_form.html.twig') }}
{% endblock %}